name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Assurez-vous que c'est le nom de votre branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .  # Le répertoire contenant vos fichiers HTML, CSS, etc.
